#!/usr/bin/ash

run_hook() {
  . /etc/btrfs-transient.sh

  mkdir /run/btrfs
  mount "$BTRFS_DEVICE" /run/btrfs
  cd /run/btrfs
  
  mkdir -p "$SNAPSHOTS_SUBVOLUME" "$TRANSIENT_SUBVOLUME"

  LAST_SNAPSHOT="$(ls -1 $SNAPSHOTS_SUBVOLUME | tail -1)"

  # If this is the first time using transient, snapshot root file system
  if [ -z "$LAST_SNAPSHOT" ]; then
    btrfs subvolume snapshot "$LIVE_SUBVOLUME" "${SNAPSHOTS_SUBVOLUME}/$(date -Iseconds)"

    [ $? -ne 0 ] && return
  fi

  # TODO: Should we backup N transient root file systems?
  btrfs subvolume snapshot "$LIVE_SUBVOLUME" "${TRANSIENT_SUBVOLUME}/$(date -Iseconds)"

  for TRANSIENT in $(ls -1 $TRANSIENT_SUBVOLUME | head -n -${TRANSIENT_RETENTION}); do
    btrfs subvolume delete "${TRANSIENT_SUBVOLUME}/${TRANSIENT}"
  done

  # TODO: Handle errors here
  btrfs subvolume delete "$LIVE_SUBVOLUME"
  btrfs subvolume snapshot "${SNAPSHOTS_SUBVOLUME}/${LAST_SNAPSHOT}" "$LIVE_SUBVOLUME"

  for SNAPSHOT in $(ls -1 $SNAPSHOTS_SUBVOLUME | head -n -${SNAPSHOTS_RETENTION}); do
    btrfs subvolume delete "${SNAPSHOTS_SUBVOLUME}/${SNAPSHOT}"
  done

  cd /
  umount /run/btrfs
}
